config/routes.rb
Rails.application.routes.draw do


  resources :tasks do
    collection { post :import }
    member do
      put :complete
      put :cancel
    end
  end
  resources :commodities
  resources :sales_terms
  resources :terms
  resources :things
  resources :lines do 
    resources :things, module: :lines 
  end

  #resources :client, only: [] do
  #  resources :sites, only: :index
  #end
  
  resources :clients do
    collection { post :import }
  end 
  resources :sites

  namespace :api, defaults: {format: 'json'} do
    namespace :v1  do
      resources :readings
    end
  end

  resources :readings
  resources :messages
  resources :assignment_items
  resources :work_items
  resources :team_assignments
  resources :photos

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  mount ActionCable.server => '/cable'
  
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
  get 'dashboard', to: 'welcome#dashbroad'
  get 'calendar', to: 'welcome#calendar'
  get 'demo', to: 'welcome#demo'
   
  get '/service-worker.js', to: 'service_workers/workers#index'
  get '/manifest.json', to: 'service_workers/manifests#index'

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    resources :collections do
      member do
        put :close
      end
      collection { post :import }
    end
    resources :folders
    resources :task_staffs
    resources :task_materials
    resources :task_vehicles
    resources :laboratories
    resources :containers do
      resources :things, module: :containers 
      member do
          put :close
      end
    end
  
    resources :sales do
      resources :folders, module: :sales
      resources :terms, module: :sales
      resources :lines, module: :sales
        resources :things
      resources :photos, only: [:create, :destroy] do
        collection do
          post :create             #-> domain.com/assignments/:id/create
          post :create_general     #-> domain.com/assignments/:id/create
          post :create_before
          post :create_after
          post :insert
        end
        member do
          put  :switch_printable     #-> domain.com/orders/:id/delete+photo
        end
      end
      member do
        put :mail
        put :confirm
        put :copy
        put :supersede
        put :cancel
        put :pend
        put :authorise
        put :deliver  
      end
    end

    resources :laboratories
    resources :products do
      collection { post :import }
    end
    resources :sale_items

    resources :works do
      get :rollback
    end
    resources :assignees
    resources :defects

    resources :locations
    resources :assignments do  
      resources :lines, module: :assignments 
        resources :things
      collection do
        get :calendar
        post :import           
      end
      member do 
          put :calendar_update  
          delete :delete_uploadfile
      end

      resource :download, only: [:show] 
      member do
          put :ask            #-> assignements/:id/start 
          put :askRequestInfo
          put :askWorkInfo
          put :approve            #-> assignements/:id/start 
          put :cancel            #-> assignements/:id/start 
          put :start            #-> assignements/:id/start 
          put :assign           #-> assignements/:id/finish
          put :quote            #-> assignements/:id/finish
          put :finish           #-> assignements/:id/finish
          put :accept           #-> assignements/:id/accept
          put :reject           #-> assignements/:id/reject
          put :acknowledge      #-> assignements/:id/acknowledge
          put :complete         #-> assignements/:id/complete 
        end
      resources :photos, only: [:create, :destroy] do 
        collection do
          post :create             #-> domain.com/assignments/:id/create
          post :create_general     #-> domain.com/assignments/:id/create
          post :create_before    
          post :create_after    
          post :insert           
        end
        member do
          put  :switch_printable     #-> domain.com/orders/:id/delete+photo
        end
      end
    end
    resources :masters do
      collection { post :import }
    end
    resources :tickets
    resources :teams do
      resources :messages
      member do
        get :chat
        patch :switch
      end
      resources :members, path: :users, module: :teams 
    end

    resources :members
    
    devise_for :users,  controllers: { sessions: "users/sessions" } 
    resources :users
    devise_scope :user do
      scope :users, as: :users do
        post 'pre_otp', to: 'users/sessions#pre_otp'
      end
    end
    resource :two_factor

    get :protected, to: 'welcome#protected'
    root 'welcome#index'
  end
end

app/models/collection.rb
class Collection < ApplicationRecord

    has_many :containers, dependent: :delete_all
    has_many :things, through: :containers

    enum status: { open: 0, close: 1 }

    def self.import(file)
        current_request_ref_no = ""
        CSV.foreach(file.path, headers: true) do |row| 
          if Collection.where(request_ref: row["request_ref"], customer_contract_no: row["customer_contract_no"] ).count == 0
            Collection.create!([
              {request_ref: row["request_ref"],
                received_date: row["received_date"],
                customer_contract_no: row["customer_contract_no"],
                request_ref: row["request_ref"],
                location: row["location"],
              },
            ])
          end
    
          collection = Collection.where(request_ref: row["request_ref"], customer_contract_no: row["customer_contract_no"] ).first
          if Container.where(collection_id: collection.id, code: row["request_ref_no"] ).count == 0
            Container.create!([
              {collection_id: collection.id,
                code: row["request_ref_no"],
                object: row["type"],
                size: row["size"],
                quantity: 1,
              }
            ])
          else
            container = Container.where(collection_id: collection.id, code: row["request_ref_no"] ).first
            container.quantity = container.quantity + 1 
            container.save
          end

          container = Container.where(collection_id: collection.id, code: row["request_ref_no"] ).first
          Thing.create!([
            {thingable_type: "Container",
             thingable_id: container.id,
             set_no: row["set_no"],
             mark: row["cube_mark"],
            }
          ])          
        end 
      end

    def to_label
      "#{customer_contract_no} #{request_ref}"
    end

    def number_of_sets 
      self.containers.count 
    end


end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :set_collection, only: [:close, :show, :edit, :update, :destroy]

  def close
    @collection.close!
    @collection.save
    redirect_to @collection
  end 

  def index
    @search = Collection.search(params[:q])
    @collections = @search.result
    @collections = Collection.where(" received_date >= ? ", Date.yesterday - 3 )  unless params[:q] 

    respond_to do |format|
      format.html
      format.csv { send_data @collections.to_csv }
      format.xls  { headers["Content-Disposition"] = "attachment; filename=\"collections.xls\"" }
    end
  end

  # GET /collections/1
  # GET /collections/1.json
  def show
  end

  # GET /collections/new
  def new
    @collection = Collection.new
  end

  # GET /collections/1/edit
  def edit
  end

  # POST /collections
  # POST /collections.json
  def create
    @collection = Collection.new(collection_params)

    respond_to do |format|
      if @collection.save
        format.html { redirect_to @collection, notice: 'Collection was successfully created.' }
        format.json { render :show, status: :created, location: @collection }
      else
        format.html { render :new }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collections/1
  # PATCH/PUT /collections/1.json
  def update
    respond_to do |format|
      if @collection.update(collection_params)
        format.html { redirect_to @collection, notice: 'Collection was successfully updated.' }
        format.json { render :show, status: :ok, location: @collection }
      else
        format.html { render :edit }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collections/1
  # DELETE /collections/1.json
  def destroy
    @collection.destroy
    respond_to do |format|
      format.html { redirect_to collections_url, notice: 'Collection was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import 
    Collection.import(params[:file])
    redirect_to collections_path, notice: "Collections imported."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collection
      @collection = Collection.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def collection_params
      params.require(:collection).permit(:customer_contract_no, :request_ref, :location, :title)
    end
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collections/_form.html.erb
<%= simple_form_for(@collection) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :customer_contract_no %>
    <%= f.input :request_ref %>
    <%= f.input :location %>
    <%= f.input :title %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/collections/edit.html.erb
<h1>Editing Collection</h1>

<%= render 'form', collection: @collection %>

<%= link_to 'Show', @collection %> |
<%= link_to 'Back', collections_path %>

app/views/collections/index.html.erb
<%= search_form_for @search do |f| %>

    <div class="row">
      <div class="col-md-2"><%= t('start_date') %></div>
      <div class="col-md-4"><%= f.date_field :received_date_gteq, as: :date_picker %></div> 
      <div class="col-md-2"><%= t('end_date') %></div>
      <div class="col-md-4"><%= f.date_field :received_date_lteq, as: :date_picker %></div>
    </div>

    <div class="row">
      <div class="col-md-2"><%= t("customer_contract_no") %></div>
      <div class="col-md-4"><%= f.search_field :customer_contract_no_cont %></div>
      <div class="col-md-2"><%= t('request_ref') %></div>
      <div class="col-md-4"><%= f.search_field :request_ref_cont %></div>
    </div>
    <div class="row">
      <div class="col-md-2"><%= t("location") %></div>
      <div class="col-md-4"><%= f.search_field :location_cont %></div>
      <div class="col-md-2"><%= t('status') %></div>
      <div class="col-md-4"><%= f.select :status_eq, Collection.statuses.to_a.map { |w| [w[0].humanize, w[1]] },
                         {:include_blank => true} %></div>
    </div>


    <br>
    <div class="actions">
      <%= f.submit 'Search' %>
    </div>
  <% end %>

<div class="card" >
  <div class="card-header">  
    <h4><%= t("collection") %>
    <%= link_to '<i class="fa fa-plus-circle"  style="color:blue"></i>'.html_safe,  
          new_collection_path, data: { turbolinks: false } %></h4>
  </div>  
  <div class="card-body">

    <table id="collections"  class="table table-striped table-bordered">
      <thead>
        <tr>
          <th><%= t("received_date") %></th>
          <th><%= t("customer_contract_no") %></th>
          <th><%= t("request_ref") %></th>
          <th><%= t("location") %></th>
          <th><%= t("number_of_sets") %></th>
          <th><%= t("status") %></th>
        </tr>
      </thead>

      <tbody>
        <% @collections.each do |collection| %>
          <tr data-link="<%= collection_path(collection) %>", data: { turbolinks: false }  >
            <td><%= collection.received_date %></td>
            <td><%= collection.customer_contract_no %></td>
            <td><%= collection.request_ref %></td>
            <td><%= collection.location  %></td>
            <td><%= collection.number_of_sets  %></td>
            <td><%= t(collection.status)  %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

  </div>
  <div class="card-footer text-muted">

      <%= form_tag import_collections_path, multipart: true do %>
        <%= file_field_tag :file %>
        <%= submit_tag "Import" %>
      <% end %>

        Download:
        <%= link_to "Excel", collections_path(request.parameters.merge(format: "xls"))%>

  </div>
</div>


<!-- Bootstrap 4 JS -->
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">

<script type="text/javascript">
  $(document).ready(function() {
    $('#collections').DataTable({
      "order": [[ 0, "desc" ]],
      "pageLength": 10
    } );
  });

  $("tr[data-link]").click(function() {
    window.location = $(this).data('link');
  });
</script>

app/views/collections/index.xls.erb
<table border="1">
    <tr>
      <th>received_date</th>
      <th>customer_contract_no</th>
      <th>request_ref</th>
      <th>location</th>
      <th>number_of_sets</th>
      <th>request_ref_no</th>
      <th>object</th>
      <th>size</th>
      <th>quantity</th>
      <th>set_no</th>
      <th>mark</th>
      <th>elabel</th>
      <th>sample_received_date</th>
    </tr>
    <% @collections.each do |collection| %>
        <% collection.containers.each do |container| %>
          <% container.things.each do |thing| %>
            <tr>
              <td><%= collection.received_date %></td>
              <td><%= collection.customer_contract_no %></td>
              <td><%= collection.request_ref %></td>
              <td><%= collection.location %></td>
              <td><%= collection.number_of_sets %></td>
              <td><%= container.code %></td>
              <td><%= container.object %></td>
              <td><%= container.size %></td>
              <td><%= container.quantity %></td>
              <td><%= thing.set_no %></td>
              <td><%= thing.mark %></td>
              <td><%= thing.code %></td>
              <td><%= thing.updated_at + 8.hours %></td>
            </tr>
          <% end %>
        <% end %>
    <% end %>
</table>

app/views/collections/new.html.erb
<h1>New Collection</h1>

<%= render 'form', collection: @collection %>

<%= link_to 'Back', collections_path %>

app/views/collections/show.html.erb
<div class="card">
  <div class="card-header">
    <div class="row">
      <div  class="col">
        <strong><%= t("collection") %>: </strong><%= @collection.id %> 
      </div>
        <%= link_to '<i class="fa fa-window-close fa-2x" ></i>'.html_safe, close_collection_path(@collection),
              data: { turbolinks: false }, method: :put  %>  
    </div>
  </div>

  <div class="card-body">

    <div class="row">
      <div  class="col-xs-4 col-md-4 ">
        <strong><%= t('customer_contract_no') %>: </strong><%= @collection.customer_contract_no %>  
      </div>
      <div  class="col-xs-4 col-md-4 ">
        <strong><%= t('request_ref') %>: </strong> <%= @collection.request_ref %>  
      </div>
      <div  class="col-xs-4 col-md-4 ">
        <strong><%= t('location') %>: </strong><%= @collection.location %>  
      </div>
    </div><br>

    <div class="album text-muted">
      <div class="container">
         <div class="row">

          <% @collection.containers.each do |container| %>
            <div class="card">
              <div class="card-header" >
                  <strong><%= t('request_ref_no') %>: </strong> 
                    <%= link_to container.code, container, data: { turbolinks: false }  %>
                  <strong><%= t('quantity') %>: </strong> <%= container.quantity %>
                  <strong><%= t('checkin_quantity') %>: </strong><%= container.checkin_quantity %>
                  <%= link_to '<i class="fa fa-window-close fa-2x" ></i>'.html_safe, close_container_path(container), 
                      data: { turbolinks: false }, method: :put  %>  
              </div>
              <div class="card-body">
                <table id="container"  class="table table-striped table-bordered">    
                  <tbody>
                    <% if container.checkin_quantity < container.quantity %>
                      <%= render partial: "things/form", locals: {thingable: container} %>
                    <% end %>
                    <%= render partial: "things/things", locals: {thingable: container} %>
                  </tbody>
                </table>
              </div>
            </div><br>
          <% end %>

        </div>
      </div>
    </div>


    <br>
     <br>

  <div class="card-footer">
    <%= link_to '<i class="fa fa-edit fa-2x" style="color:blue"></i>'.html_safe, edit_collection_path(@collection), 
        data: { turbolinks: false }  %> 
    <%= link_to '<i class="fa fa-trash fa-2x" style="color:red"></i>'.html_safe, @collection, 
        data: { turbolinks: false }, method: :delete, data: {confirm: "Are your sure? "}  %> 
    <%= link_to '<i class="fa fa-list-alt fa-2x"  style="color:blue"></i>'.html_safe,  
        collections_path, data: { turbolinks: false } %>
    <%= link_to '<i class="fa fa-plus-circle fa-2x"  style="color:blue"></i>'.html_safe,  
        new_collection_path, data: { turbolinks: false } %> 
  </div>
</div>