config/routes.rb
Rails.application.routes.draw do


  resources :tasks do
    collection { post :import }
    member do
      put :complete
      put :cancel
    end
  end
  resources :commodities
  resources :sales_terms
  resources :terms
  resources :things
  resources :lines do 
    resources :things, module: :lines 
  end

  #resources :client, only: [] do
  #  resources :sites, only: :index
  #end
  
  resources :clients do
    collection { post :import }
  end 
  resources :sites

  namespace :api, defaults: {format: 'json'} do
    namespace :v1  do
      resources :readings
    end
  end

  resources :readings
  resources :messages
  resources :assignment_items
  resources :work_items
  resources :team_assignments
  resources :photos

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  mount ActionCable.server => '/cable'
  
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
  get 'dashboard', to: 'welcome#dashbroad'
  get 'calendar', to: 'welcome#calendar'
  get 'demo', to: 'welcome#demo'
   
  get '/service-worker.js', to: 'service_workers/workers#index'
  get '/manifest.json', to: 'service_workers/manifests#index'

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    resources :collections do
      member do
        put :close
      end
      collection { post :import }
    end
    resources :folders
    resources :task_staffs
    resources :task_materials
    resources :task_vehicles
    resources :laboratories
    resources :containers do
      resources :things, module: :containers 
      member do
          put :close
      end
    end
  
    resources :sales do
      resources :folders, module: :sales
      resources :terms, module: :sales
      resources :lines, module: :sales
        resources :things
      resources :photos, only: [:create, :destroy] do
        collection do
          post :create             #-> domain.com/assignments/:id/create
          post :create_general     #-> domain.com/assignments/:id/create
          post :create_before
          post :create_after
          post :insert
        end
        member do
          put  :switch_printable     #-> domain.com/orders/:id/delete+photo
        end
      end
      member do
        put :mail
        put :confirm
        put :copy
        put :supersede
        put :cancel
        put :pend
        put :authorise
        put :deliver  
      end
    end

    resources :laboratories
    resources :products do
      collection { post :import }
    end
    resources :sale_items

    resources :works do
      get :rollback
    end
    resources :assignees
    resources :defects

    resources :locations
    resources :assignments do  
      resources :lines, module: :assignments 
        resources :things
      collection do
        get :calendar
        post :import           
      end
      member do 
          put :calendar_update  
          delete :delete_uploadfile
      end

      resource :download, only: [:show] 
      member do
          put :ask            #-> assignements/:id/start 
          put :askRequestInfo
          put :askWorkInfo
          put :approve            #-> assignements/:id/start 
          put :cancel            #-> assignements/:id/start 
          put :start            #-> assignements/:id/start 
          put :assign           #-> assignements/:id/finish
          put :quote            #-> assignements/:id/finish
          put :finish           #-> assignements/:id/finish
          put :accept           #-> assignements/:id/accept
          put :reject           #-> assignements/:id/reject
          put :acknowledge      #-> assignements/:id/acknowledge
          put :complete         #-> assignements/:id/complete 
        end
      resources :photos, only: [:create, :destroy] do 
        collection do
          post :create             #-> domain.com/assignments/:id/create
          post :create_general     #-> domain.com/assignments/:id/create
          post :create_before    
          post :create_after    
          post :insert           
        end
        member do
          put  :switch_printable     #-> domain.com/orders/:id/delete+photo
        end
      end
    end
    resources :masters do
      collection { post :import }
    end
    resources :tickets
    resources :teams do
      resources :messages
      member do
        get :chat
        patch :switch
      end
      resources :members, path: :users, module: :teams 
    end

    resources :members
    
    devise_for :users,  controllers: { sessions: "users/sessions" } 
    resources :users
    devise_scope :user do
      scope :users, as: :users do
        post 'pre_otp', to: 'users/sessions#pre_otp'
      end
    end
    resource :two_factor

    get :protected, to: 'welcome#protected'
    root 'welcome#index'
  end
end

app/views/shared/_favicon.html.erb
<% %w(76 120 152 167 180).each do |size| %>
  <%= favicon_link_tag "Icon-#{size}.png", rel: 'apple-touch-icon', type: 'image/png', sizes: "#{size}x#{size}" %>
<% end %>

<% %w(16 32).each do |size| %>
  <%= favicon_link_tag "Icon-#{size}.png", rel: 'icon', type: 'image/png', sizes: "#{size}x#{size}" %>
<% end %>

app/views/shared/_head.html.erb
<title><%= t('brand') %></title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= action_cable_meta_tag %>

<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'assignment_calendar', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'assignments' %>
<%= javascript_pack_tag 'teams' %>
<%= javascript_pack_tag 'tasks' %>
<%= javascript_pack_tag 'cable' %>

<%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
<link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

 <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

 <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
 <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
 <script>
 $( function() {
    $( '#accordion' ).accordion({
    active: false,
    heightStyle: "content",
    collapsible: true
    });
 } );
 </script>
 
<!-- Lighthouse Details -->
<link rel="manifest" href="/manifest.json">
<meta name="theme-color" content="#C50001"/>

<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black">
<meta name="apple-mobile-web-app-title" content="fieldConnect">

<meta name="msapplication-TileImage" content="/app/assets/images/icon-144.png">
<meta name="msapplication-TileColor" content="#fff">

<link rel="apple-touch-icon" href="/example.png">

<%= favicon_link_tag "Icon-76.png", rel: 'apple-touch-icon', type: 'image/png', sizes: "76x76" %>
<%= favicon_link_tag "Icon-120.png", rel: 'apple-touch-icon', type: 'image/png', sizes: "120x120" %>
<%= favicon_link_tag "Icon-152.png", rel: 'apple-touch-icon', type: 'image/png', sizes: "152x152" %>
<%= favicon_link_tag "Icon-167.png", rel: 'apple-touch-icon', type: 'image/png', sizes: "167x167" %>
<%= favicon_link_tag "Icon-180.png", rel: 'apple-touch-icon', type: 'image/png', sizes: "180x180" %>

<%= favicon_link_tag "favicon-16x16.png", rel: 'icon', type: 'image/png', sizes: "16x16" %>
<%= favicon_link_tag "favicon-32x32.png", rel: 'icon', type: 'image/png', sizes: "32x32" %>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |key, value| %>
      <% type = key.to_s.gsub('alert','error').gsub('notice','success') %>
      toastr['<%= type %>']('<%= value %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_navbar.html.erb
<% if user_masquerade? %>
  <div class="alert alert-warning text-center">
    You're logged in as <b><%= current_user.name %> (<%= current_user.email %>)</b>
    <%= link_to back_masquerade_path(current_user) do %><%= icon("fas", "times") %> Logout <% end %>
  </div>
<% end %>

<nav class="navbar navbar-expand-md navbar-light bg-light">
  <div class="container">
    <%= link_to Rails.configuration.application_name, root_path, class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarMain" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarMain">
      <ul class="navbar-nav mr-auto mt-2 mt-md-0">
      </ul>

      <ul class="navbar-nav">
        <li class="nav-item"><%= link_to "What's New", announcements_path, class: "nav-link #{unread_announcements(current_user)}" %></li>
        <% if user_signed_in? %>

        <li class="nav-item">
          <%= link_to notifications_path, class: "nav-link" do %>
            <span><i class="far fa-bell" aria-hidden="true"></i></span>
          <% end %>
         </li>

          <li class="nav-item dropdown">

            <div id="nav-account-dropdown" class="dropdown-menu dropdown-menu-right" aria-labelledby="navbar-dropdown">
              <% if current_user.admin? %>
                <%= link_to "Admin Area", admin_root_path, class: "dropdown-item" %>
              <% end %>
              <%= link_to "Settings", edit_user_registration_path, class: "dropdown-item" %>
              <div class="dropdown-divider"></div>
              <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>

        <% else %>
          <li class="nav-item"><%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "Login", new_user_session_path, class: "nav-link" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_notices.html.erb
    <% unless flash.blank? %>
       <% flash.each do |type, message| %>
          <div class="alert <%= flash_class(type.to_s) %>">
             <button class="close" data-dismiss="alert">x</button>
          <%= message %>
          </div>
       <% end %>
    <% end %>

app/views/shared/_notification.html.erb
<% unless flash.empty? %>
    <script>
        <% flash.each do |key, value| %>
          <% type = key.to_s.gsub('alert', 'error').gsub('notice', 'success') %>
          new Noty ({
              type: '<%= type %>',
              layout: 'topRight',
              timeout: '3000',
              theme: 'sunset',
              text: '<%= value %>'
          }).show();
        <% end %>
    </script>
<% end %>

app/views/shared/_sidebar.html.erb
    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion toggled" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <% if user_signed_in? %>
          <%=link_to dashboard_path, data: { turbolinks: false }, class:"sidebar-brand d-flex align-items-center justify-content-center" do%>
          <i class="fas fa-hard-hat fa-2x" style="color:yellow"></i>
          <div class="sidebar-brand-text mx-3"><%= t("brand") %> <sup>4.0</sup></div>
          <%end%>
      <% else %>
        <%= content_tag :li ,class: "nav-item active" do%>
          <%=link_to root_path, data: { turbolinks: false }, class:"sidebar-brand d-flex align-items-center justify-content-center" do%>
          <i class="fas fa-hard-hat fa-2x" style="color:yellow"></i>
          <div class="sidebar-brand-text mx-3"><%= t("brand") %> <sup>4.0</sup></div>
          <%end%>
        <%end%>
      <% end %>

      <!-- Divider -->
      <% if user_signed_in? %>
      
        <hr class="sidebar-divider"></hr>
        <div class="sidebar-heading">
          <%= t('task') %>
        </div>
          <%=link_to dashboard_path, data: { turbolinks: false }, :title => t('dashboard'), class:"sidebar-brand d-flex align-items-center justify-content-center" do%>
            <i class="fas fa-chart-line fa-2x"></i><%= t('dashboard') %>
          <% end %>
          <%=link_to clients_path, data: { turbolinks: false }, :title => t('client'),  class:"sidebar-brand d-flex align-items-center justify-content-center" do%>
            <i class="fas fa-address-card fa-2x"></i><%= t('client') %>
          <% end %><i>
          <%=link_to sales_path(:commit => "Search"), data: { turbolinks: false }, :title => t('quotation'),  class:"sidebar-brand d-flex align-items-center justify-content-center" do%>
            <i class="fas fa-book fa-2x"></i><%= t('quotation') %>
          <% end %>
          <%=link_to tasks_path, data: { turbolinks: false }, :title => t('work'), class:"sidebar-brand d-flex align-items-center justify-content-center" do%>
            <i class="fas fa-tasks fa-2x"></i><%= t('task') %>
          <% end %>
          <%=link_to collections_path, data: { turbolinks: false }, :title => t('collections'), class:"sidebar-brand d-flex align-items-center justify-content-center" do%>
            <i class="fas fa-box fa-2x"></i><%= t('collection') %>
          <% end %>

<!-- Heading 
          <%=link_to products_path, data: { turbolinks: false }, :title => t('products'), class:"sidebar-brand d-flex align-items-center justify-content-center" do%>
            <i class="fas fa-key fa-2x"></i><%= t('product') %>
          <% end %>
          <%=link_to laboratories_path, data: { turbolinks: false }, :title => t('laboratory'), class:"sidebar-brand d-flex align-items-center justify-content-center" do%>
            <i class="fas fa-flask fa-2x"></i><%= t('laboratory') %>
          <% end %>
          <%=link_to terms_path, data: { turbolinks: false }, :title => t('terms'), class:"sidebar-brand d-flex align-items-center justify-content-center" do%>
            <i class="fas fa-handshake fa-2x"></i><%= t('terms') %>
          <% end %>
-->

        <!-- Heading -->
        <hr class="sidebar-divider"></hr>
        <div class="sidebar-heading">
          <%= t('admin') %>
        </div>

        <!-- 
          <%=link_to demo_path, data: { turbolinks: false }, :title => t('terms'), class:"sidebar-brand d-flex align-items-center justify-content-center" do%>
            <i class="fas fa-video fa-2x"></i><%= t('demo') %>
          <% end %>

        <!-- Nav Item - Teams Collapse Menu 
        <% if current_user.SysAdmin? %> 

          <li class="nav-item">
            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTeams" aria-expanded="true" aria-controls="collapseTeams">
              <i class="fas fa-fw fa-users  fa-2x"></i>
              <span><%= t('team') %></span>
            </a>
            <div id="collapseTeams" class="collapse" aria-labelledby="headingTeams" data-parent="#accordionSidebar">
              <div class="bg-white py-2 px-3  collapse-inner rounded">

                <% current_user.teams.each do |team| %>
                  <tr>
                    <a class="collapse-item"></a>
                    <td><i class="fa fa-users "></i> <%= link_to team.display_name, team   %> </td>
                  </tr>
                <% end %>

              </div>
            </div>
          </li>

          <!-- Nav Item - Pages Collapse Master Menu -->
          <li class="nav-item">
            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
              <i class="fas fa-fw fa-cog  fa-2x"></i>
              <span><%= t('setting') %></span>
            </a>
            <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
              <div class="bg-white py-2 px-4 collapse-inner rounded">
                <h5 class="collapse-header"><%= t('setting') %></h5>
                  <% if current_user.SysAdmin?  %>
                    <a class="collapse-item"></a>
                    <td><i class="fa fa-edit"></i> <%= link_to t('user'), users_path, data: { turbolinks: false } %></td>
                    <a class="collapse-item"></a>
                    <td><i class="fa fa-edit"></i> <%= link_to t('team'), teams_path, data: { turbolinks: false } %></td>
                    <a class="collapse-item"></a>
                    <td><i class="fa fa-edit"></i> <%= link_to t('product'), products_path, data: { turbolinks: false } %></td>
                    <a class="collapse-item"></a>
                    <td><i class="fa fa-edit"></i> <%= link_to t('term'), terms_path, data: { turbolinks: false } %></td>
                    <a class="collapse-item"></a>
                    <td><i class="fa fa-edit"></i> <%= link_to t('SysTable'), master_path(id: 1), data: { turbolinks: false } %></td>
                    <a class="collapse-item"></a>
                    <td><i class="fa fa-edit"></i> <%= link_to t('laboratory'), laboratories_path, data: { turbolinks: false } %></td>
                    <a class="collapse-item"></a>
                    <% end %>
              </div>
            </div>
          </li>
          
        <% end %>

<!-- Nav Item - Utilities Collapse Menu 
      <% if current_user.SysAdmin? %>
          <li class="nav-item">
            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities" aria-expanded="true" aria-controls="collapseUtilities">
              <i class="fas fa-fw fa-wrench  fa-2x"></i>
              <span>Utilities</span>
            </a>
            <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
              <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Custom Utilities:</h6>
                <a class="collapse-item" href="utilities-color.html">Colors</a>
                <a class="collapse-item" href="utilities-border.html">Borders</a>
                <a class="collapse-item" href="utilities-animation.html">Animations</a>
                <a class="collapse-item" href="utilities-other.html">Other</a>
              </div>
            </div>
          </li>
        <% end %>
      <% end %>
   
      <!-- End of User Login 
        <!-- Nav Chat - Teams Collapse Menu 
        <li class="nav-item">
          <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseChats" aria-expanded="true" aria-controls="collapseTeams">
            <i class="fas fa-fw fa-comments fa-2x"></i>
            <span><%= t('chatroom') %></span>
          </a>
          <div id="collapseChats" class="collapse" aria-labelledby="headingChats" data-parent="#accordionSidebar">
            <div class="bg-white py-2 px-3  collapse-inner rounded">
              <h6 class="collapse-header">
                  </i> <%= link_to t('chatrooms'), teams_path %> 
              </h6>

            </div>
          </div>
        </li>
-->


      <!-- Divider -->
      <hr class="sidebar-divider d-none d-md-block">

      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>

    </ul>
    <!-- End of Sidebar -->

<script type="text/javascript">
    $(document).ready(function() {
        $("#sidebarToggle").click(function(e) {
            e.preventDefault();           
            $("#accordionSidebar").toggleClass("toggled");
            $('#accordionSidebar.toggled').find("#sidebar-wrapper").find(".collapse").collapse('hide');
        });
    });
</script>

app/views/shared/_sidebar.js.erb
if (Notification.permission === 'granted') {
  var title = 'FieldGood Notification'
  var body = 'Triggered by link on the <%= Rails.env %> environment.'
  var options = { body: body }
  new Notification(title, options)
}

app/views/shared/_topbar.html.erb
<% if user_masquerade? %>
  <div class="alert alert-warning text-center">
    You're logged in as <b><%= current_user.name %> (<%= current_user.email %>)</b>
    <%= link_to back_masquerade_path(current_user) do %><%= icon("fas", "times") %> Logout <% end %>
  </div>
<% end %>
        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

          <!-- Sidebar Toggle (Topbar) -->
          <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
          </button>

          <!-- Topbar Search -->
          <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
            <div class="input-group">
              <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
              <div class="input-group-append">
                <button class="btn btn-primary" type="button">
                  <i class="fas fa-search fa-sm"></i>
                </button>
              </div>
            </div>
          </form>

          <!-- Topbar Navbar -->
          <ul class="navbar-nav ml-auto">

            <!-- Nav Item - Search Dropdown (Visible Only XS) -->
            <li class="nav-item dropdown no-arrow d-sm-none">
              <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
              </a>
              <!-- Dropdown - Messages -->
              <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
                <form class="form-inline mr-auto w-100 navbar-search">
                  <div class="input-group">
                    <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                    <div class="input-group-append">
                      <button class="btn btn-primary" type="button">
                        <i class="fas fa-search fa-sm"></i>
                      </button>
                    </div>
                  </div>
                </form>
              </div>
            </li>

          <% if user_signed_in? %>
            <!-- Nav Item - Alerts -->
            <li class="nav-item dropdown no-arrow mx-1 my-3">
              <%= link_to tickets_path, data: { turbolinks: false } do %>
                <i class="fa fa-bell fa-2x icon-babu"></i>
                <span class="badge badge-danger badge-counter" id="navbar_num_of_unread"><%= current_user.unread if current_user.unread > 0 %></span>
              <% end %>
            </li>
            
            <div class="topbar-divider d-none d-sm-block"></div>

            <!-- Nav Item - User Information -->
          <%# if user_signed_in? %>
            <li class="nav-item dropdown no-arrow">
              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-900 small"><%= current_user.name %><br><h6><%= current_team.display_name %></h6></span>
                
                <%= image_tag user_avatar(current_user.email, 35), class: "rounded-circle" %>
              </a>
              <!-- Dropdown - User Information -->
              <div class="dropdown-menu px-4 dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
 
                  <a class="dropdown-item" ></a>
                  <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-600"></i>
                  <%=  link_to t("profile"), edit_user_registration_path, class: 'border-t text-xs uppercase font-bold text-gray-800 no-underline block px-6 py-3 bg-white hover:bg-gray-300 whitespace-no-wrap'  %>

                <div class="dropdown-divider"></div>
                  <a class="dropdown-item" ></a>
                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                  <%= link_to t('logout'), destroy_user_session_path, method: :delete  %>
              </div>
            </li>
          <% else %>
            <div class="z-10 inline-flex items-center align-middle leading-none rounded no-underline text-gray-700 hover:text-gray-800 hover:bg-white py-4">
              <%#= link_to 'Log In', new_user_session_path, class: 'btn btn-primary' %>
              <%= link_to ('<i class="fa fa-sign-in-alt fa-fw fa-2x"></i>').html_safe, new_user_session_path  %>
            </div>
          <% end %>
          <div class="z-10 inline-flex items-center align-middle leading-none rounded no-underline text-gray-700 hover:text-gray-800 hover:bg-white my-2">
              <% if I18n.locale == :zh %> 
                  <li><%= link_to image_tag("hkflag32.png") , url_for( :locale => 'en' ), data: { turbolinks: false }, class: "nav-link"  %></li>    
              <% else %>
                  <li><%= link_to image_tag("usflag32.png") , url_for( :locale => 'zh' ), data: { turbolinks: false }, class: "nav-link"  %></li>
              <% end %>
          </div>

        </nav>
        <!-- End of Topbar -->
<script type="text/javascript">
    $(document).ready(function() {
        $("#sidebarToggleTop").click(function(e) {
            e.preventDefault();
            $("#accordionSidebar").toggleClass("toggled");
            $('#accordionSidebar.toggled').find("#sidebar-wrapper").find(".collapse").collapse('hide');
        });
    });
</script>

app/views/shared/pdf_header.html.erb
<html>
  <head>
  </head>
  <body>
    <table style="height: 50px; line-height: 3px;">
        <tbody>
          <tr>
              <td style="width: 65px; padding-left: 00px;">
                  <%= image_tag image_url('HKT-logo.jpeg'), size: "98x98" %>
              </td>
              <td style="width: 35px; padding-left: 00px;">
              </td>
              <td style="width: 800px;">
                <h2 style="font-size: 21px;"><b>香港試驗有限公司</b></h2>
                <h2 style="font-size: 21px;"><b>HONG KONG TESTING CO., LTD.</b></h2>
                <p style="font-size: 12px;">Room 205, 2/F, Fuk Shing Commercial Building, 28 On Lok Mun Street, On Lok Tsuen, Fanling, N.T. Hong Kong</p>
                <p style="font-size: 12px;">Tel: (852) 2692 2171&nbsp; Fax: (852) 2691 4874&nbsp; Email: info@hktesting.com.hk</a></p>
                <p style="font-size: 12px;">Website: www.hktesting.com.hk</p>
                <p style="font-size: 12px;">地址：香港新界粉嶺安樂村安樂門街28號福成商業大廈2樓205室 電話: (852)2692 2171&nbsp; 傳真: (852) 2691 4874</p>
              </td>
              <td>
                <%= @svg.html_safe %>
              </td>
          <tr>
              <td colspan="12">
                <h3 style="text-align: center;"><u><%= @sale.category.upcase %></u></h3>
              </td>
          </tr>
        </tbody>
    </table>

    <table style="height: 50px; line-height: 3px;">
        <tbody>
          <tr>
            <td style="width: 525px;">
                <strong><%= @sale.category %> No.: </Strong><%= @sale.our_ref %>
              <% if @sale.parent_id? %>
                ( <strong>supersede: </Strong><%= @sale.parent.our_ref %> )
              <% end %>     
            </td>
            <td style="width: 400px;">
                <strong><%= @sale.category %> Date: </Strong><%= @sale.sale_date %>
            </td>
          </tr>
        </tbody>
    </table>
  </body>
</html>

app/views/shared/pdf_quotation_list_header.html.erb
<html>
  <head>
  </head>
  <body>
    <table >
        <tbody>
          <tr>
            <td style="width: 440px; font-size: 16px; ">
              <p><br><br>Quotation Date From: <%= @start_date %> To: <%= @end_date %> </p>
            </td>
            <td style="width: 380px; text-align: center; ">
                <b style="font-size: 24px; ">Hong Kong Testing Co., Ltd.</b>
                Quotation summary
            </td>
            <td style="width: 440px; font-size: 16px; text-align: right; ">
            <br>
                <div class="page-count" style="text-align: right;" >
                    <span class="page"></span> of <span class="topage"></span>
                    <br>Report Date: <%= Date.today %>
                </div>
            </td>
          </tr>
        </tbody>
    </table>
  </body>
</html>