config/routes.rb
Rails.application.routes.draw do


  resources :tasks do
    collection { post :import }
    member do
      put :complete
      put :cancel
    end
  end
  resources :commodities
  resources :sales_terms
  resources :terms
  resources :things
  resources :lines do 
    resources :things, module: :lines 
  end

  #resources :client, only: [] do
  #  resources :sites, only: :index
  #end
  
  resources :clients do
    collection { post :import }
  end 
  resources :sites

  namespace :api, defaults: {format: 'json'} do
    namespace :v1  do
      resources :readings
    end
  end

  resources :readings
  resources :messages
  resources :assignment_items
  resources :work_items
  resources :team_assignments
  resources :photos

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  mount ActionCable.server => '/cable'
  
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
  get 'dashboard', to: 'welcome#dashbroad'
  get 'calendar', to: 'welcome#calendar'
  get 'demo', to: 'welcome#demo'
   
  get '/service-worker.js', to: 'service_workers/workers#index'
  get '/manifest.json', to: 'service_workers/manifests#index'

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    resources :collections do
      member do
        put :close
      end
      collection { post :import }
    end
    resources :folders
    resources :task_staffs
    resources :task_materials
    resources :task_vehicles
    resources :laboratories
    resources :containers do
      resources :things, module: :containers 
      member do
          put :close
      end
    end
  
    resources :sales do
      resources :folders, module: :sales
      resources :terms, module: :sales
      resources :lines, module: :sales
        resources :things
      resources :photos, only: [:create, :destroy] do
        collection do
          post :create             #-> domain.com/assignments/:id/create
          post :create_general     #-> domain.com/assignments/:id/create
          post :create_before
          post :create_after
          post :insert
        end
        member do
          put  :switch_printable     #-> domain.com/orders/:id/delete+photo
        end
      end
      member do
        put :mail
        put :confirm
        put :copy
        put :supersede
        put :cancel
        put :pend
        put :authorise
        put :deliver  
      end
    end

    resources :laboratories
    resources :products do
      collection { post :import }
    end
    resources :sale_items

    resources :works do
      get :rollback
    end
    resources :assignees
    resources :defects

    resources :locations
    resources :assignments do  
      resources :lines, module: :assignments 
        resources :things
      collection do
        get :calendar
        post :import           
      end
      member do 
          put :calendar_update  
          delete :delete_uploadfile
      end

      resource :download, only: [:show] 
      member do
          put :ask            #-> assignements/:id/start 
          put :askRequestInfo
          put :askWorkInfo
          put :approve            #-> assignements/:id/start 
          put :cancel            #-> assignements/:id/start 
          put :start            #-> assignements/:id/start 
          put :assign           #-> assignements/:id/finish
          put :quote            #-> assignements/:id/finish
          put :finish           #-> assignements/:id/finish
          put :accept           #-> assignements/:id/accept
          put :reject           #-> assignements/:id/reject
          put :acknowledge      #-> assignements/:id/acknowledge
          put :complete         #-> assignements/:id/complete 
        end
      resources :photos, only: [:create, :destroy] do 
        collection do
          post :create             #-> domain.com/assignments/:id/create
          post :create_general     #-> domain.com/assignments/:id/create
          post :create_before    
          post :create_after    
          post :insert           
        end
        member do
          put  :switch_printable     #-> domain.com/orders/:id/delete+photo
        end
      end
    end
    resources :masters do
      collection { post :import }
    end
    resources :tickets
    resources :teams do
      resources :messages
      member do
        get :chat
        patch :switch
      end
      resources :members, path: :users, module: :teams 
    end

    resources :members
    
    devise_for :users,  controllers: { sessions: "users/sessions" } 
    resources :users
    devise_scope :user do
      scope :users, as: :users do
        post 'pre_otp', to: 'users/sessions#pre_otp'
      end
    end
    resource :two_factor

    get :protected, to: 'welcome#protected'
    root 'welcome#index'
  end
end

app/models/team_assignment.rb
class TeamAssignment < ApplicationRecord
  belongs_to :team
  belongs_to :assignment
end

app/controllers/team_assignments_controller.rb
class TeamAssignmentsController < ApplicationController
  before_action :set_team_assignment, only: [:show, :edit, :update, :destroy]

  # GET /team_assignments
  # GET /team_assignments.json
  def index
    @team_assignments = TeamAssignment.all
  end

  # GET /team_assignments/1
  # GET /team_assignments/1.json
  def show
  end

  # GET /team_assignments/new
  def new
    @team_assignment = TeamAssignment.new
  end

  # GET /team_assignments/1/edit
  def edit
  end

  # POST /team_assignments
  # POST /team_assignments.json
  def create
    @team_assignment = TeamAssignment.new(team_assignment_params)

    respond_to do |format|
      if @team_assignment.save
        format.html { redirect_to @team_assignment, notice: 'Team assignment was successfully created.' }
        format.json { render :show, status: :created, location: @team_assignment }
      else
        format.html { render :new }
        format.json { render json: @team_assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /team_assignments/1
  # PATCH/PUT /team_assignments/1.json
  def update
    respond_to do |format|
      if @team_assignment.update(team_assignment_params)
        format.html { redirect_to @team_assignment, notice: 'Team assignment was successfully updated.' }
        format.json { render :show, status: :ok, location: @team_assignment }
      else
        format.html { render :edit }
        format.json { render json: @team_assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /team_assignments/1
  # DELETE /team_assignments/1.json
  def destroy
    @team_assignment.destroy
    respond_to do |format|
      format.html { redirect_to team_assignments_url, notice: 'Team assignment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team_assignment
      @team_assignment = TeamAssignment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def team_assignment_params
      params.require(:team_assignment).permit(:team_id, :assignment_id, :role_id)
    end
end

app/helpers/team_assignments_helper.rb
module TeamAssignmentsHelper
end

app/views/team_assignments/_form.html.erb
<%= simple_form_for(@team_assignment) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :team %>
    <%= f.association :assignment %>
    <%= f.input :role_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/team_assignments/edit.html.erb
<h1>Editing Team Assignment</h1>

<%= render 'form', team_assignment: @team_assignment %>

<%= link_to 'Show', @team_assignment %> |
<%= link_to 'Back', team_assignments_path %>

app/views/team_assignments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Team Assignments</h1>

<table>
  <thead>
    <tr>
      <th>Team</th>
      <th>Assignment</th>
      <th>Role</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @team_assignments.each do |team_assignment| %>
      <tr>
        <td><%= team_assignment.team_id %></td>
        <td><%= team_assignment.assignment_id %></td>
        <td><%= team_assignment.role_id %></td>
        <td><%= link_to 'Show', team_assignment %></td>
        <td><%= link_to 'Edit', edit_team_assignment_path(team_assignment) %></td>
        <td><%= link_to 'Destroy', team_assignment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Team Assignment', new_team_assignment_path %>

app/views/team_assignments/new.html.erb
<h1>New Team Assignment</h1>

<%= render 'form', team_assignment: @team_assignment %>

<%= link_to 'Back', team_assignments_path %>

app/views/team_assignments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Team:</strong>
  <%= @team_assignment.team_id %>
</p>

<p>
  <strong>Assignment:</strong>
  <%= @team_assignment.assignment_id %>
</p>

<p>
  <strong>Role:</strong>
  <%= @team_assignment.role_id %>
</p>

<%= link_to 'Edit', edit_team_assignment_path(@team_assignment) %> |
<%= link_to 'Back', team_assignments_path %>