config/routes.rb
Rails.application.routes.draw do


  resources :tasks do
    collection { post :import }
    member do
      put :complete
      put :cancel
    end
  end
  resources :commodities
  resources :sales_terms
  resources :terms
  resources :things
  resources :lines do 
    resources :things, module: :lines 
  end

  #resources :client, only: [] do
  #  resources :sites, only: :index
  #end
  
  resources :clients do
    collection { post :import }
  end 
  resources :sites

  namespace :api, defaults: {format: 'json'} do
    namespace :v1  do
      resources :readings
    end
  end

  resources :readings
  resources :messages
  resources :assignment_items
  resources :work_items
  resources :team_assignments
  resources :photos

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  mount ActionCable.server => '/cable'
  
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
  get 'dashboard', to: 'welcome#dashbroad'
  get 'calendar', to: 'welcome#calendar'
  get 'demo', to: 'welcome#demo'
   
  get '/service-worker.js', to: 'service_workers/workers#index'
  get '/manifest.json', to: 'service_workers/manifests#index'

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    resources :collections do
      member do
        put :close
      end
      collection { post :import }
    end
    resources :folders
    resources :task_staffs
    resources :task_materials
    resources :task_vehicles
    resources :laboratories
    resources :containers do
      resources :things, module: :containers 
      member do
          put :close
      end
    end
  
    resources :sales do
      resources :folders, module: :sales
      resources :terms, module: :sales
      resources :lines, module: :sales
        resources :things
      resources :photos, only: [:create, :destroy] do
        collection do
          post :create             #-> domain.com/assignments/:id/create
          post :create_general     #-> domain.com/assignments/:id/create
          post :create_before
          post :create_after
          post :insert
        end
        member do
          put  :switch_printable     #-> domain.com/orders/:id/delete+photo
        end
      end
      member do
        put :mail
        put :confirm
        put :copy
        put :supersede
        put :cancel
        put :pend
        put :authorise
        put :deliver  
      end
    end

    resources :laboratories
    resources :products do
      collection { post :import }
    end
    resources :sale_items

    resources :works do
      get :rollback
    end
    resources :assignees
    resources :defects

    resources :locations
    resources :assignments do  
      resources :lines, module: :assignments 
        resources :things
      collection do
        get :calendar
        post :import           
      end
      member do 
          put :calendar_update  
          delete :delete_uploadfile
      end

      resource :download, only: [:show] 
      member do
          put :ask            #-> assignements/:id/start 
          put :askRequestInfo
          put :askWorkInfo
          put :approve            #-> assignements/:id/start 
          put :cancel            #-> assignements/:id/start 
          put :start            #-> assignements/:id/start 
          put :assign           #-> assignements/:id/finish
          put :quote            #-> assignements/:id/finish
          put :finish           #-> assignements/:id/finish
          put :accept           #-> assignements/:id/accept
          put :reject           #-> assignements/:id/reject
          put :acknowledge      #-> assignements/:id/acknowledge
          put :complete         #-> assignements/:id/complete 
        end
      resources :photos, only: [:create, :destroy] do 
        collection do
          post :create             #-> domain.com/assignments/:id/create
          post :create_general     #-> domain.com/assignments/:id/create
          post :create_before    
          post :create_after    
          post :insert           
        end
        member do
          put  :switch_printable     #-> domain.com/orders/:id/delete+photo
        end
      end
    end
    resources :masters do
      collection { post :import }
    end
    resources :tickets
    resources :teams do
      resources :messages
      member do
        get :chat
        patch :switch
      end
      resources :members, path: :users, module: :teams 
    end

    resources :members
    
    devise_for :users,  controllers: { sessions: "users/sessions" } 
    resources :users
    devise_scope :user do
      scope :users, as: :users do
        post 'pre_otp', to: 'users/sessions#pre_otp'
      end
    end
    resource :two_factor

    get :protected, to: 'welcome#protected'
    root 'welcome#index'
  end
end

app/controllers/sales/folders_controller.rb
class Sales::FoldersController < FoldersController
    before_action :load_foldable

  def index
    @folders = @foldable.folders

  end
  
  # PATCH/PUT /folders/1.json
  def update
    respond_to do |format|
      if @folder.update(folder_params)
        format.js {}
        format.html { redirect_to @folder, notice: 'Folder was successfully updated.' }
        format.json { render :show, status: :ok, location: @folder }
      else
        format.html { render :edit }
        format.json { render json: @folder.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
      @folder = Folder.find(params[:id])
      @folder.destroy

      respond_to do |format|
        format.html { redirect_to @foldable, notice: 'Folder was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
  
      def load_foldable
        @foldable = Sale.find(params[:sale_id])
      end
  end

app/controllers/sales/lines_controller.rb
class Sales::LinesController < LinesController
    before_action :load_lineable

  def index
    @lines = @lineable.lines

  end
  
  # PATCH/PUT /lines/1.json
  def update
    respond_to do |format|
      if @line.update(line_params)
        format.js {}
        format.html { redirect_to @line, notice: 'Line was successfully updated.' }
        format.json { render :show, status: :ok, location: @line }
      else
        format.html { render :edit }
        format.json { render json: @line.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
      @line = Line.find(params[:id])
      @line.destroy

      respond_to do |format|
        format.html { redirect_to @lineable, notice: 'Line was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
  
      def load_lineable
        @lineable = Sale.find(params[:sale_id])
      end
  end

app/controllers/sales/terms_controllers.rb
class Sales::TermsControllers < TermsController
    before_action :set_term, only: [:show, :edit, :update, :destroy]
  
    # GET /terms
    # GET /terms.json
    def index
      @terms = Term.all
    end
  
    # GET /terms/1
    # GET /terms/1.json
    def show
    end
  
    # GET /terms/new
    def new
      @term = Term.new
    end
  
    # GET /terms/1/edit
    def edit
    end
  
    # POST /terms
    # POST /terms.json
    def create
      @term = Term.new(term_params)
  
      respond_to do |format|
        if @term.save
          format.html { redirect_to @term, notice: 'Term was successfully created.' }
          format.json { render :show, status: :created, location: @term }
        else
          format.html { render :new }
          format.json { render json: @term.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PATCH/PUT /terms/1
    # PATCH/PUT /terms/1.json
    def update
      respond_to do |format|
        if @term.update(term_params)
          format.html { redirect_to @term, notice: 'Term was successfully updated.' }
          format.json { render :show, status: :ok, location: @term }
        else
          format.html { render :edit }
          format.json { render json: @term.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /terms/1
    # DELETE /terms/1.json
    def destroy
      @term.destroy
      respond_to do |format|
        format.html { redirect_to terms_url, notice: 'Term was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_term
        @term = Term.find(params[:id])
      end
  
      # Only allow a list of trusted parameters through.
      def term_params
        params.require(:term).permit(:code, :description, :name, :local_name)
      end
  end
  

app/controllers/sales_controller.rb
class SalesController < ApplicationController

  before_action :authenticate_user!
  before_action :set_sale, only: [:show, :edit, :update, :destroy, :cancel, :copy, :supersede, 
    :mail, :confirm, :pend, :authorise, :deliver]

  def copy
    @new_sale = @sale.dup
    @new_sale.parent_id = nil  
    @new_sale.remarks = @sale.remarks
    @new_sale.aasm_state = "prepared" 
    @new_sale.save
    @sale.lines.each do | line |
      new_line = line.dup
      new_line.lineable = @new_sale
      new_line.save
    end

    @sale.terms.each do | saleterm |
      new_saleterm = SalesTerm.new  
      new_saleterm.term_id = saleterm.id 
      new_saleterm.sale  = @new_sale
      new_saleterm.save
    end

    redirect_to @new_sale 
  end 

  def supersede
    @new_sale = @sale.dup
    @new_sale.parent_id = @sale.id 
    @new_sale.remarks = @sale.remarks
    if @sale.aasm_state = "prepared"   
      @sale.cancel! 
    end
    @new_sale.aasm_state = "prepared" 
    @new_sale.save
    @sale.lines.each do | line |
      new_line = line.dup
      new_line.lineable = @new_sale
      new_line.save
    end

    @sale.terms.each do | saleterm |
      new_saleterm = SalesTerm.new  
      new_saleterm.term_id = saleterm.id 
      new_saleterm.sale  = @new_sale
      new_saleterm.save
    end

    redirect_to @new_sale 
  end 

  def mail
    @sale.mail! 
    redirect_to @sale 
  end 

  def confirm
    @sale.confirm! 
    redirect_to @sale 
  end 

  def cancel
    @sale.cancel! 
    redirect_to @sale 
  end 

  def pend
    @sale.pend! 
    redirect_to @sale 
  end 

  def authorise
    @sale.authorise! 
    @sale.authorised_date = Date.today
    @sale.save
    redirect_to @sale 
  end 

  def deliver
    @sale.deliver! 
    redirect_to @sale 
  end 

  def show
    #@salepath = @sale.our_ref
    #@salepath = (request.base_url + request.fullpath).from(0).to(-5)
    @qrcode = RQRCode::QRCode.new(@sale.our_ref)
    @svg = @qrcode.as_svg(
      offset: 0,
      color: '000',
      shape_rendering: 'crispEdges',
      module_size: 4
      )
    @photos = @sale.photos
    respond_to do |format|
      format.html {}
      format.pdf do
        pdf = WickedPdf.new.pdf_from_string(
          render_to_string(template: 'sales/show.pdf.erb',  layout: 'layouts/application.pdf.erb'),
          margin: { top: 48, bottom: 64},
          header: {
            content: render_to_string(        
               template: 'shared/pdf_header.html.erb',
               layout: 'layouts/application.pdf.erb'
            )
          },
          footer: {
            content: render_to_string(
              template: 'shared/pdf_footer.html.erb',
              layout: 'layouts/application.pdf.erb'
            )
          }
        )
        send_data(pdf, filename: "#{@sale.our_ref}.pdf", type: 'application/pdf', disposition: :attachment)
      end
    end
  end

  def index
    if params[:commit] == "Search" or params[:commit] == "Summary" or params[:commit] == "Report"
      @search = Sale.search(params[:q])
      @sales = @search.result
      @sales = Sale.where(" sale_date >= ? ", Date.yesterday - 6 ) unless params[:q]
      @count = @sales.count
      if @count > 0
        @start_date = @sales.last.sale_date
        @end_date = @sales.first.sale_date
      end

      if @count > 0 and params[:commit] == "Summary" 
        pdf = WickedPdf.new.pdf_from_string(
          render_to_string(template: 'sales/index.pdf.erb', layout: 'layouts/application.pdf.erb'),
          orientation: 'Landscape',  
          margin: { top: 25, bottom: 8},
          header: {
            content: render_to_string(        
            template: 'shared/pdf_quotation_list_header.html.erb',
            layout: 'layouts/application.pdf.erb'
            )
          },
        )
        send_data(pdf, filename: 'quotation.pdf', type: 'application/pdf', disposition: :attachment )
      end
    else
      if params[:aasm_state].present?
        @sales = current_team.sales.where(aasm_state: params[:aasm_state])
      else
        @sales = current_team.sales
      end
    end

  end

  def new
    @sale = Sale.new
    if params[:client_id].present?
      @sale.client_id = params[:client_id]
    end
    @sale.team = current_team
    if params[:category] ==  "Invoice"
      @sale.category = "Invoice"
    else
      @sale.category = "Quotation"
    end
    @sale.sale_date = Date.today
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)
    @sale.phone = @sale.client.phone if @sale.client_id? and @sale.phone.nil?
    @sale.address = @sale.client.address if @sale.client_id? and @sale.phone.nil?
    @sale.project_site = @sale.client.site if @sale.client_id? and @sale.phone.nil?

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    term_details = ""
    @sale.term_ids.each do |term|
      term_details = term_details + Term.find(term).name.gsub(/\n/, '<br/>') 
    end
    @sale.remarks = term_details

    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
      @photoable = @sale
      @photos = @photoable.photos 
    end

    # Only allow a list of trusted parameters through.
    def sale_params
      params.require(:sale).permit(:team_id, :category, :sale_date, :our_ref, :client_ref, 
        :client_id, :project_site, :attention, :phone, :total_amount, :authorised_person, 
        :authorised_date, :aasm_state, :remarks, :term_id, :term_details, :address, 
        :ship_client_id, :ship_project_site, :ship_attention, :ship_phone, :fax, :email, :cc, 
        :ship_contact, :contact, :ship_to, :ship_to_address, :discount, :authorised_person2,
        :uploadfile, term_ids: [], product_ids: [], photos: [] )
    end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
<%= simple_form_for(@sale) do |f| %>
<div class="card">
  <div class="card-header">
    <%#= t(@sale.category) %>
    <%#= @sale.our_ref %> 
    <div class="row ">
      <div class="col-xs-6 col-md-6  ">
        <%= f.input :our_ref %>
      </div>
      <div class="col-xs-6 col-md-6  ">
        <%= f.input :sale_date, as: :date, html5: true %>
      </div>
    </div>
  </div>
  <div class="card-body">

    <%= f.input :team_id, :as => :hidden %>
    <%= f.input :category, :as => :hidden %>
    <%= f.input :client_id, :as => :hidden %>

    <div class="form-inputs">
      <div class="row ">
        <div class="col-xs-6 col-md-6  ">
          <%= f.input :client_ref %>
          <%= f.association :client %>
          <% if @sale.client_id? %><br>
            <%= @sale.client.name %><br>
            (<%= @sale.client.code %>:<%= @sale.client.site %>)<br>
          <% if @sale.client.address1? %>
            <%= @sale.client.address1 %><br>
          <% end %>
          <% if @sale.client.address2? %>
            <%= @sale.client.address2 %><br>
          <% end %>
          <% if @sale.client.address3? %>
            <%= @sale.client.address3 %><br>
          <% end %>
          <% if @sale.client.address4? %>
            <%= @sale.client.address4 %><br>
          <% end %>
          <% end %>

        </div>
      <div class="col-xs-6 col-md-6  ">
          <%= f.input :ship_to %>
          <%= f.input :ship_to_address, label: t('ship_to_address') , as: :rich_text_area  %>
        </div>
      </div>

      <div class="row ">
        <div class="col-xs-4 col-md-4  ">
          <%= f.input :attention %>
          <%= f.input :phone  %>
          <%= f.input :fax %>
          <%= f.input :email  %>
        </div>

        <div class="col-xs-4 col-md-4  ">
          <%= f.input :cc %>
          <%= f.input :authorised_person %>
          <%= f.input :authorised_person2 %>
          <%= f.input :discount %>
        </div>

        <div class="col-xs-4 col-md-4  ">
          <%= f.input :ship_contact %>
          <%= f.input :ship_phone  %>
        </div>
      </div>

      <div class="row ">
        <div class="col-xs-12 col-md-12  ">
          <%= f.association :products, label: t('product'), as: :select2, collection: Product.Service, multiple: true  %>
          <%#= f.association :products, label: t('product'), as: :check_boxes, collection: Product.Service  %>
        </div>
      </div>

      <% if @sale.category == "Quotation" %>

        <div class="listcontainer">
          <%= f.association :terms, as: :check_boxes %>
        </div>
 
      <% end %>

      <div class="row ">
        <div class="col-xs-12 col-md-12  ">
          <%= f.input :remarks, as: :rich_text_area  %>
        </div>
      </div>

    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>


  </div>
  <% end %>
</div>
<div class="card-footer text-muted">
  <%= link_to t('list'), sales_path, data: { turbolinks: false }, class: 
  "btn btn-tab btn-warning btn-tab "  %> 

  <%#= link_to '<i class="fa fa-list-alt fa-2x" style="color:blue"></i>'.html_safe, 
    sales_path %>
</div>
</div>

<script type="text/javascript">
  $(".taggable").select2(
    tags: $('.taggable').data('options')
     width: "252px"
  );
</script>

app/views/sales/_workflow_sales.html.erb
<% if @sale.prepared? %>
    <div class="btn-group d-flex" role="group" aria-label="...">
      <%= link_to t('cancel'), cancel_sale_path(@sale), method: :put, data: { turbolinks: false }, class: "btn btn-tab btn-info btn-tab col "  %> 
      <%= link_to t('mail'), mail_sale_path(@sale), method: :put, data: { turbolinks: false }, class: "btn btn-tab btn-warning btn-tab col"  %> 
      <%= link_to t('confirm'), confirm_sale_path(@sale), method: :put, data: { turbolinks: false }, class: "btn btn-tab btn-primary btn-tab col"  %> 
    </div>
<% end %>

<% if @sale.mailed? %>
    <div class="btn-group d-flex" role="group" aria-label="...">
      <%= link_to t('cancel'), cancel_sale_path(@sale), method: :put, data: { turbolinks: false }, class: "btn btn-tab btn-info btn-tab col "  %> 
      <%= link_to t('confirm'), confirm_sale_path(@sale), method: :put, data: { turbolinks: false }, class: "btn btn-tab btn-warning btn-tab col"  %> 
    </div>
<% end %>

<% if @sale.confirmed? %>
    <div class="btn-group d-flex" role="group" aria-label="...">
      <%= link_to t('cancel'), cancel_sale_path(@sale), method: :put, data: { turbolinks: false }, class: "btn btn-tab btn-info btn-tab col "  %> 
    </div>
<% end %>

app/views/sales/edit.html.erb
<%= render 'form', sale: @sale %>

app/views/sales/index.html.erb
      <%= search_form_for @search do |f| %>
 
      <div class="row">
        <div class="col-md-2"><%= t('start_date') %></div>
        <div class="col-md-4"><%= f.date_field :sale_date_gteq, as: :date_picker %></div> 
        <div class="col-md-2"><%= t('end_date') %></div>
        <div class="col-md-4"><%= f.date_field :sale_date_lteq, as: :date_picker %></div>
      </div>

      <div class="row">
        <div class="col-md-2"><%= t('our_ref') %></div>
        <div class="col-md-4"><%= f.search_field :our_ref_cont %></div>
        <div class="col-md-2"><%= t('client_ref') %></div>
        <div class="col-md-4"><%= f.search_field :client_ref_cont %></div>
      </div>
      <br>

      <div class="actions"><%= f.submit 'Search' %>
        <% if @count > 0  %>
          <%= f.submit 'Summary' %>
        <% end %> 
      </div>
    <% end %>

<div class="card" >

  <div class="card-body">
    <table id="sales" class="table table-striped table-bordered">
      <thead>
          <tr>
            <th><%= t('sale_date') %></th> 
            <th style="width: 8%"><%= t('our_ref') %></th>
            <th><%= t('client') %></th>
            <th><%= t('site') %></th>
            <th><%= t('testing') %></th>
            <th><%= t('contact') %></th>
            <th><%= t('aasm_state') %></th>
          </tr>
      </thead>
      <tbody>
        <% @sales.each do |sale| %>
          <tr data-link="<%= sale_path(sale) %>">
            <td><%= sale.sale_date %></td>
            <td><%= sale.our_ref %><br><%= sale.client_ref %></td>
            <td><b><%= sale.client.code %> <%= sale.client.client_name %></b></td>
            <td>
                <% if sale.client.parent_id? %>
                  <%= sale.client.site %> <%= sale.client.name %>
                <% end %>
            </td>
            <td>
              <% current_category = "XXX" %>
              <% sale.lines.each do |line| %>
                <% if current_category != line.category %>
                  <%= line.category %><br> 
                  <% current_category = line.category %>
                <% end %>
              <% end %>
            </td>
            <td><% if sale.contact? %>
                  <b><%= sale.contact %></b><br>
                <% end %>
                <% if sale.phone? %>
                  Phone: <%= sale.phone %><br>
                <% end %>
                <% if sale.fax? %>
                  Fax: <%= sale.fax %><br>
                <% end %>
                <%= sale.email %>
            </td>
            <td><%= t(sale.aasm_state) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%#= paginate @sales %>
  </div>
  <div class="card-footer text-muted">
    <%= link_to t('add'), new_sale_path, data: { turbolinks: false }, class: 
    "btn btn-tab btn-warning btn-tab "  %> 
  </div>
</div>

<!-- Bootstrap 4 JS -->
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">

<script type="text/javascript">
  $(document).ready(function() {
    $('#sales').DataTable({
        "order": [[ 1, "desc" ]]
    } );
  });

  $("tr[data-link]").click(function() {
    window.location = $(this).data('link');
  });

</script>

app/views/sales/new.html.erb
<%= render 'form', sale: @sale %>

app/views/sales/show.html.erb
<div class="card" style="width: 1000px">
  <div class="card-header">
    <div class="row">
      <div class="col">
        <%= name_avatar(@sale.category.upcase, 24) %> 
        <%= t(@sale.category) %>(<%= @sale.our_ref %>)
        <% if @sale.parent_id? %>
          <%= link_to @sale.parent.our_ref, sale_path(@sale.parent), data: { turbolinks: false }, 
          class: "btn btn-sm btn-warning"  %> 
        <% end %>
      </div>
        <%= link_to [@sale, format: :pdf], data: { turbolinks: false } do %>
            <i class="fa fa-file-pdf fa-2x" aria-hidden="true"></i>
        <% end %>
    </div>


  <div class="card-body">

    <div class="row "> 
      <div  class="col-xs-4 col-md-4  ">
        <strong><%= t('client') %>: </strong> 
        <%= @sale.client.client_name %> <br>
        <%= @sale.client.address1 %><br>
        <%= @sale.client.address2 %><br>
        <%= @sale.client.address3 %><br>
        <%= @sale.client.address4 %><br>
      </div>
      <div  class="col-xs-4 col-md-4  ">
        <strong><%= t('site') %>: </strong><%= @sale.project_site %><br>
        <strong><%= t('attention') %>: </strong><%= @sale.attention %> <br>
        <strong><%= t('phone') %>: </strong><%= @sale.phone %><br>
        <strong><%= t('fax') %>: </strong><%= @sale.fax %><br>
        <strong><%= t('email') %>: </strong><%= @sale.email %><br> 
        <strong><%= t('cc') %>: </strong><%= @sale.cc %> 
      </div>
      <div  class="col-xs-4 col-md-4  ">
        <strong><%= t('sale_date') %>: </strong><%= @sale.sale_date %><br>
        <strong><%= t('status') %>: </strong><%= t(@sale.aasm_state) %><br>
        <strong><%= t('client_ref') %>: </strong><%= @sale.client_ref %><br>
        <strong><%= t('authorised_person') %>: </strong><%= @sale.authorised_person %><br> 
        <strong><%= t('authorised_person2') %>: </strong><%= @sale.authorised_person2 %> 
      </div>
    </div>

    <br>
 
    <div class="card">
      <div class="card-header">
          <%= t('lines') %> 
      </div>
      <div class="card-body">
        <%= render partial: "lines/lines", locals: {lineable: @sale} %>
        <%#= render partial: "lines/form", locals: {lineable: @sale} %>
      </div>
      <div class="card-footer">
        <% if current_user.Engineer? or current_user.SysAdmin?  %>
          <%= link_to t('edit'), sale_lines_path(@sale), data: { turbolinks: false }, 
            class: "btn btn-tab btn-warning btn-tab "  %> 
        <% end %>
      </div>
    </div> <br>
 
      <div class="row ">
      <div  class="col-xs-4 col-md-4  ">
        <strong><%= t('status') %>: </strong>
        <%= t(@sale.aasm_state) %>
      </div>
      <div  class="col-xs-4 col-md-4  ">
        <strong><%= t('discount') %>: </strong>
        <%= @sale.discount %>%
      </div>
      <div  class="col-xs-4 col-md-4  ">
          <strong><%= t('total_amount') %>: </strong>
          <%= number_to_currency(@sale.calc_amount, unit: '$', precision: 0) %>
        </div>
      </div>
      <br>

  </div>
  <div class="card-footer text-muted">
    <div class="btn-group d-flex" role="group" aria-label="...">
      <%= link_to t('quotation'), sales_path(:commit => "Search"), data: { turbolinks: false }, class: "btn btn-sm btn-default btn-tab col "  %> 
      <%= link_to t('supersede'), supersede_sale_path(@sale), method: :put, data: { turbolinks: false }, class: "btn btn-tab btn-danger col "  %> 
      <%= link_to t('copy'), copy_sale_path(@sale), method: :put, data: { turbolinks: false }, class: "btn btn-tab btn-info col "  %> 
      <% if current_user.Engineer? or current_user.SysAdmin?  %>
        <%= link_to t('edit'), edit_sale_path(@sale), data: { turbolinks: false }, class: "btn btn-tab btn-warning col "  %> 
      <% end %>
    </div>
  </div>
</div>

<%= render 'photo_upload' %>

  <% if @sale.uploadfile.attached? %>
   <div class="row ">
      <div  class="col-xs-12 col-md-12  ">
        <strong><%= t('delivered-file') %>:  </strong> 
        <%#= link_to @sale.uploadfile.filename, rails_blob_path(@sale.uploadfile, 
          disposition: :attachment) %>
        <%= link_to url_for(@sale.uploadfile), 
                class: "btn btn-sm btn-warning" do %>
            <i class="fas fa-paperclip fa-lg p-r-5"></i> 
            <%= @sale.uploadfile.filename %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<br>

<%= render partial: "workflow_sales" %><br>

<div class="card">
  <div class="card-header "> 
    <%= t("terms") %>
  </div>
  <div class="card-body "> 
    <% @sale.terms.order(code: :desc).each do |term| %>
        <p><%= term.code %>: <%= term.name %><p>         
    <% end %>
  </div>
</div><br>

<div class="card">
  <div class="card-header "> 
    <%= t("remarks") %>
  </div>
  <div class="card-body "> 
    <%= @sale.remarks %>
  </div>
</div><br>

<script type="text/javascript">
    $("tr[data-link]").click(function() {
        window.location = $(this).data('link');
    });
</script> 